export const dummyExpenses = [
  {
    id: "1",
    amount: 50,
    date: "2024-01-01",
    category: "Food",
    description: "Lunch with friends",
    paymentMethod: "cash",
  },
  {
    id: "2",
    amount: 150,
    date: "2024-02-02",
    category: "Utilities",
    description: "Electricity bill",
    paymentMethod: "credit",
  },
  {
    id: "3",
    amount: 200,
    date: "2024-03-03",
    category: "Transportation",
    description: "Gas for the car",
    paymentMethod: "cash",
  },
  {
    id: "4",
    amount: 100,
    date: "2024-04-04",
    category: "Entertainment",
    description: "Movie tickets",
    paymentMethod: "credit",
  },
  {
    id: "5",
    amount: 75,
    date: "2024-05-05",
    category: "Groceries",
    description: "Weekly grocery shopping",
    paymentMethod: "cash",
  },
  {
    id: "6",
    amount: 300,
    date: "2024-06-06",
    category: "Travel",
    description: "Flight tickets",
    paymentMethod: "credit",
  },
  {
    id: "7",
    amount: 125,
    date: "2024-07-07",
    category: "Clothing",
    description: "New jacket",
    paymentMethod: "cash",
  }
];
